---
title: "temp"
author: "Lachlan Moody"
date: "28/08/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(tidyverse)
library(ggplot2)
library(leaflet)
```

## R Markdown

```{r}
Locations <- read_csv("data/Pedestrian_Counting_System_-_Sensor_Locations (Exercise 2).csv")


Counts <- read_csv("data/Pedestrian_Counting_System_2019 (Exercise 2).csv")

Counts$Day <- factor(Counts$Day, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))

Counts <- Counts %>%
  mutate(Sensor_Name = if_else(Sensor_Name == "Collins St (North)", "Collins Street (North)", Sensor_Name)) %>%
   mutate(Sensor_Name = if_else(Sensor_Name == "Flinders la - Swanston St (West) Temp", "Flinders La - Swanston St (West) Temporary", Sensor_Name)) %>%
  mutate(Sensor_Name = if_else(Sensor_Name == "Flinders La - Swanston St (West) Temp", "Flinders La - Swanston St (West) Temporary", Sensor_Name)) %>%
  mutate(Sensor_Name = if_else(Sensor_Name == "Lincoln-Swanston(West)", "Lincoln-Swanston (West)", Sensor_Name)) %>%
  mutate(Sensor_Name = if_else(Sensor_Name == "Pelham St (S)", "Pelham St (South)", Sensor_Name))
  
Locations <-  Locations %>%
  mutate(sensor_name = if_else(sensor_name == "Melbourne Central-Elizabeth St (East)Melbourne Central-Elizabeth St (East)", "Melbourne Central-Elizabeth St (East)", sensor_name)) %>%
  mutate(sensor_name = if_else(sensor_name == "Building 80 RMIT", "Swanston St - RMIT Building 80", sensor_name)) %>%
  mutate(sensor_name = if_else(sensor_name == "RMIT Building 14", "Swanston St - RMIT Building 14", sensor_name))


Total_Counts <- Counts %>%
  group_by(Sensor_Name) %>%
  summarise(average = mean(Hourly_Counts))



Combined <- Total_Counts %>% 
  left_join(Locations, by = c("Sensor_Name" = "sensor_name"))



Daily_Counts <- Counts %>%
  group_by(Sensor_Name, Time, Day) %>%
  summarise(average = mean(Hourly_Counts))

Plot_Daily <- Daily_Counts %>%
  ggplot(aes(x = Time,
             y = average,
             group = Sensor_Name)) +
  geom_line() +
  facet_wrap(~Day)

Plot_Daily
```


```{r map}
Plot_Map <- Combined %>%
  leaflet() %>%
  addProviderTiles("CartoDB.DarkMatter") %>%
  addCircles(~longitude, ~latitude, 
             radius = ~average/20, 
             label = ~as.character(Sensor_Name),
             col = "pink")

Plot_Map
```

